[project]
name = "CicloAPI"
version = "0.0.1"
description = "AAPI para el proyecto de ciclovías"
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
    "bcrypt>=4.2.1",
    "fastapi==0.115.6",
    "passlib>=1.7.4",
    "pyjwt==2.10.1",
    "python-multipart==0.0.20",
    "uvicorn==0.34.0",
]
