[project]
name = "cicloapi"
version = "0.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M. Herrero", email = "mherrero@bsc.es" }
]
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.2.1",
    "fastapi",
    "pyjwt",
    "python-multipart",
    "uvicorn",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
packages = ["cicloapi"]
package-dir = {"" = "src"}

[project.scripts]
cicloapi = "cicloapi.__init__:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["cicloapi*"]

[tool.setuptools.package_data]
"cicloapi" = [
    "src/cicloapi/data/*.json",
    "src/cicloapi/*.py",
]